name: gplus-CI
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Installation depends
      run: |
        ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        brew install protobuf
        brew install gflags
        brew install glog
        brew install tree
        git clone http://github.com/google/googletest
        cd googletest
        echo `cmake --version`
        mkdir build && cd build
        echo "running cmake ..."
        cmake .. -DCMAKE_CXX_STANDARD=11
        echo "running make ..."
        make
        echo "running install ..."
        make install

    - name: Checkout
      uses: actions/checkout@master

    - name: Check Source Code Dir
      run: |
        pwd
        tree .

    - name: Build
      run: |
        mkdir logdir
        ./release.sh >> ./logdir/release.log

    - name: Run TestCases and Generate Report
      run: |
        ./build/leetcode >> ./logdir/testcase_report.txt
        
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: TestcaseReport
        path: ./logdir
